# Generated by Django 5.2.15 on 2026-06-22 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_savedproperty_unit_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('call', 'Phone call'), ('whatsapp', 'WhatsApp'), ('viewing_request', 'Viewing request')], max_length=30)),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(choices=[('fake', 'Looks fake or suspicious'), ('unavailable', 'Unit is no longer available'), ('wrong_price', 'Price is wrong'), ('wrong_location', 'Location is wrong'), ('other', 'Other issue')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='source',
            field=models.CharField(blank=True, help_text='Where the lead came from, for example viewing_form.', max_length=40),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['is_published', 'area'], name='rentals_bui_is_publ_fc1c05_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['latitude', 'longitude'], name='rentals_bui_latitud_6e32dd_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['updated_at'], name='rentals_bui_updated_371512_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status', 'rent'], name='rentals_uni_status_5f2934_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type', 'status'], name='rentals_uni_unit_ty_f472f7_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['updated_at'], name='rentals_uni_updated_0bb651_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['created_at'], name='rentals_vie_created_b95847_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['unit', 'created_at'], name='rentals_vie_unit_id_0c20ff_idx'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_leads', to='rentals.unit'),
        ),
        migrations.AddField(
            model_name='contactlead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rentals.building'),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='rentals.unit'),
        ),
        migrations.AddIndex(
            model_name='contactlead',
            index=models.Index(fields=['method', 'created_at'], name='rentals_con_method_2b5bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlead',
            index=models.Index(fields=['unit', 'created_at'], name='rentals_con_unit_id_0d784e_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['status', 'created_at'], name='rentals_lis_status_68f43d_idx'),
        ),
        migrations.AddIndex(
            model_name='listingreport',
            index=models.Index(fields=['building', 'created_at'], name='rentals_lis_buildin_7853ea_idx'),
        ),
    ]
