# Generated by Django 5.2.15 on 2026-06-23 06:34

import rentals.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_contactlead_listingreport_viewingrequest_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, upload_to='building_images/', validators=[rentals.images.validate_upload_image_size]),
        ),
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='unit_images/', validators=[rentals.images.validate_upload_image_size]),
        ),
    ]
