# Generated by Django 5.2.15 on 2026-06-16

from django.db import migrations, models
from django.utils import timezone


def approve_existing_admins(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    for profile in Profile.objects.select_related('user').filter(user__is_staff=True):
        profile.role = 'admin'
        profile.approval_status = 'approved'
        profile.phone_verified = True
        profile.approved_at = timezone.now()
        profile.save(update_fields=['role', 'approval_status', 'phone_verified', 'approved_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(approve_existing_admins, migrations.RunPython.noop),
    ]
